image: docker

stages:
  - lint
  - test

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  - docker-compose version

lint:
  stage: lint
  script:
    - docker-compose -f compose/test/docker-compose.test.yml build
    - docker-compose -f compose/test/docker-compose.test.yml run unbfeelings yarn lint

test:
  stage: test
  script:
    - docker-compose -f compose/test/docker-compose.test.yml build
    - docker-compose -f compose/test/docker-compose.test.yml run unbfeelings yarn test-with-coverage
