apiVersion: "extensions/v1beta1"
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: gcr.io/unbfeelings/app
---
apiVersion: v1
kind: Service
metadata:
  name: app-port
spec:
  selector:
    app: app
  ports:
    - name: app-port
      port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort
---
